export const sumInsuredLabels = {
    buildingSi: 'Building SI',
    buildingSI: 'Building SI',
    buildingSumInsured: 'Building',
    businessInterruptionSi: 'Business Interruption SI',
    businessInterruptionSI: 'Business Interruption SI',
    earthquakeSi: 'Earthquake SI',
    earthquakeSI: 'Earthquake SI',
    fffSi: 'FFF SI',
    furnitureFixturesFittingsSI: 'Furniture Fixtures & Fittings SI',
    furnitureFixturesFittingsSumInsured: 'Furniture Fixtures & Fittings',
    machineryBreakdownSi: 'Machinery Breakdown SI',
    machineryBreakdownSI: 'Machinery Breakdown SI',
    machineryBreakdownSumInsured: 'Machinery Breakdown SI',
    mlopSi: 'MLOP SI',
    otherContentsSi: 'Other Contents SI',
    otherContentsSI: 'Other Contents SI',
    otherContentsSumInsured: 'Other Contents',
    plantMachinerySi: 'Plant & Machinery SI',
    plantAndMachinerySI: 'Plant & Machinery SI',
    plantAndMachinerySumInsured: 'Plant & Machinery',
    stfiSi: 'STFI SI',
    stfiSI: 'STFI SI',
    stockSi: 'Stock SI',
    stockSI: 'Stock SI',
    stockSumInsured: 'Stock',
    terrorismSi: 'Terrorism SI',
    terrorismSI: 'Terrorism SI',
    totalSi: 'Total SI',
    totalSumInsured: 'Total SI',
    fireSumInsured: 'Fire SI',
    fireSectionSumInsured: 'Fire Section Sum Insured',
    burglarySumInsured: 'Burglary SI',
    burglarySectionSumInsured: 'Burglary Section Sum Insured',
    boilerPressurePlantSumInsured: 'Boiler Pressure Plant SI',
    electronicEquipmentSumInsured: 'Electronic Equipment SI',
    portableEquipmentSumInsured: 'Portable Equipment SI',
    moneySumInsured: 'Money SI',
    fidelitySumInsured: 'Fidelity SI',
    personalAccidentSumInsured: 'Personal Accident SI',
    businessInterruptionSumInsured: 'Business Interruption SI',
    publicLiabilitySumInsured: 'Public Liability SI',
    plateGlassSumInsured: 'Plate Glass SI',
};

export const discountLabels = {
    iibDiscountPct: 'IIB Discount (%)',
    iibDiscountPercent: 'IIB Discount (%)',
    eqDiscountPct: 'Earthquake Discount (%)',
    eqDiscountPercent: 'Earthquake Discount (%)',
    stfiDiscountPct: 'STFI Discount (%)',
    stfiDiscountPercent: 'STFI Discount (%)',
    natcatDiscountPercent: 'Natcat Discount (%)',
};

export const rateLabels = {
    iibRate: 'IIB Rate',
    netIIBRate: 'Net IIB Rate',
    earthquakeRate: 'Earthquake Rate',
    eqRate: 'Earthquake Rate',
    stfiRate: 'STFI Rate',
    netIibRate: 'Net IIB Rate',
    netEqRate: 'Net Earthquake Rate',
    netStfiRate: 'Net STFI Rate',
    netNatCatRate: 'Net Nat Cat Rate',
    netCatRate: 'Net Cat Rate',
    terrorismRate: 'Terrorism Rate',
    terrorismApplied: 'Terrorism Applied',
    finalFireRate: 'Final Fire Rate',
    totalFireRate: 'Total Fire Rate',
    fireRate: 'Fire Rate',
    bhbRate: 'BHB Rate',
    rate: 'Rate',
    basis: 'Basis',
};

export const premiumLabels = {
    firePremium: 'Fire Premium',
    terrorismPremium: 'Terrorism Premium',
    fireSectionPremium: 'Fire Section Premium',
    biPremium: 'Business Interruption Premium',
    businessInterruptionPremium: 'Business Interruption Premium',
    mbPremium: 'Machinery Breakdown Premium',
    machineryBreakdownPremium: 'Machinery Breakdown Premium',
    mlopPremium: 'MLOP Premium',
    burglaryPremium: 'Burglary Premium',
    boilerPressurePlantPremium: 'Boiler Pressure Plant Premium',
    electronicEquipmentPremium: 'Electronic Equipment Premium',
    portableEquipmentPremium: 'Portable Equipment Premium',
    moneyInsurancePremium: 'Money Insurance Premium',
    fidelityGuaranteePremium: 'Fidelity Guarantee Premium',
    personalAccidentPremium: 'Personal Accident Premium',
    publicLiabilityPremium: 'Public Liability Premium',
    plateGlassPremium: 'Plate Glass Premium',
    netPremium: 'Net Premium',
    gst: 'GST',
    gstPercent: 'GST (%)',
    gstAmount: 'GST Amount',
    grossPremium: 'Gross Premium',
};

export const calculationSectionLabels = {
    sumInsured: 'Sum Insured Details',
    discounts: 'Discounts',
    discountsApplied: 'Discounts',
    rates: 'Rates',
    premiums: 'Premium Breakdown',
    premiumSummary: 'Premium Summary',
    premium: 'Premium',
    summary: 'Premium Summary',
    sectionWiseSumInsured: 'Section Wise Sum Insured',
    sectionWisePremiums: 'Section Wise Premiums',
    sectionRatesUsed: 'Section Rates Used',
    fireRateBreakdown: 'Fire Rate Breakdown',
    policyDetails: 'Policy Details',
};
